apiVersion: apps/v1
kind: Deployment
metadata:
  name: string
spec:
  replicas: 1
  selector:
    matchLabels:
      app: string
  template:
    metadata:
      labels:
        app: string
    spec:
      containers:
        - name: string
          image: string:latest
          # imagePullPolicy: Always
          ports:
            - containerPort: 2410

